services:
    web:
        image: nginx:latest
        depends_on:
            - php
        volumes:
            - ./:/var/www/html:ro,cached
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8001:80"

    php:
        container_name: php
        build:
            context: ./docker/php
        depends_on:
            - db
        volumes:
            - .:/var/www
            - ./docker/php/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./docker/php/config/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        expose:
            - 9000

    db:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: symfony
            MYSQL_ROOT_PASSWORD: 5up3r53cre7
        ports:
            - "3307:3306"